# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip | cat && test ${PIPESTATUS} -eq 0
            pip install --progress-bar=off -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python setup.py test
      - run:
          name: Build a source distribution and wheel
          command: |
            . venv/bin/activate
            pip install --progress-bar=off wheel
            python setup.py sdist
            python setup.py bdist_wheel
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: ~/workspace
    docker:
      - image: circleci/python:3.6
    steps:
      - attach_workspace:
          at: .
      - run:
          name: verify git tag vs. version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: upload to pypi
          command: |
            ls -l dist/*
            . venv/bin/activate
            pip install twine
            twine upload dist/*
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+(\.\d+){2}((a|b|rc)\d+)?(\.post\d+)?(\.dev\d+)?/
# 
#   workflows:
#     version: 2
#     build_and_deploy:
#       jobs:
#         - build
#         - build:
#             filters:
#               tags:
#                 only: /.*/
#         - deploy:
#             requires:
#               - build
#             filters:
#               tags:
#                 only: /[0-9]+(\.[0-9]+)*/
#               branches:
#                 ignore: /.*/
